# file=open("C:\\Users\\User\\Desktop\\mukesh.txt",'r')
# reading=file.read()
# print(reading)
# file.close()
# file=open("C:\\Users\\User\\Desktop\\mukesh.txt",'w')
# writing=file.write("I am in python AI class")
# print(writing)
# file.close()
# file=open("C:\\Users\\User\\Desktop\\mukesh.txt",'a')
# appending=file.write("\n my name is mukesh singh")
# print(appending)
# file.close()
# file=open("C:\\Users\\User\\Desktop\\mukesh.txt",'r')
# # reading=file.readlines()
# reading=file.readline()
# print(reading)
# file.close()
# with open("C:\\Users\\User\\Desktop\\mukesh.txt",'r') as file:
#     reading=file.read()
# print(reading)
# file=open("m.txt",'x')
# file=open("m.txt",'w')
# file=open("m.txt",'a')
# # writing=file.write("my name is mukesh singh")
# # print(writing)
# append=file.write("\n this is a python class")
# print(append)
# file.close()
file=open("m.txt",'w+')
writing=file.write("hi mukesh")
print(writing)
file.close()
with open("m.txt",'+a') as f1:
   writing=f1.write("\n learning python")
with open("m.txt",'r') as f2:
   reading=f2.readlines()
print(writing)
print(reading)